<?php
/**
 * Created by PhpStorm.
 * User: arevkina
 * Date: 04.10.2017
 * Time: 15:42
 */

namespace Skytech;
use function htmlentities;

class Order
{
    public  $operation;
    private $orderid; /** @var int unique order id generated by TWEC PG */
    private $xid; /** @var int unique order id  generated by merchant */
    private $orderdate;
    private $language;
    private $amount;
    private $currency;
    private $description;
    private $operationtype;
    private $orderstatus;
    private $sessionid;
    private $merchantid;
    private $fee;
    private $url;
    public $customer; /** @var Customer */
    public $recipient; /** @var Customer   */
    public $transdata; /** @var TransData  */
    public $card;
    private $status; /** @var  int  */
    private $origamount;
    private $origcurrency;
    private $orderexpperiod;
    private $vendorid;

    function __construct(Customer $customer,TransData $transdata=null,Card $card=null, Customer $recipient=null)
    {
        $this->orderdate = time();
        $this->customer = $customer;
        $this->recipient = $recipient;
        $this->transdata = $transdata;
        $this->card = $card;
    }

    /**
     * @return mixed
     */
    public function getVendorid()
    {
        return $this->vendorid;
    }

    /**
     * @param mixed $vendorid
     */
    public function setVendorid($vendorid)
    {
        $this->vendorid = $vendorid;
    }

    /**
     * @return mixed
     */
    public function getOrderexpperiod()
    {
        return $this->orderexpperiod;
    }

    /**
     * @param mixed $orderexpperiod
     */
    public function setOrderexpperiod($orderexpperiod)
    {
        $this->orderexpperiod = $orderexpperiod;
    }
    /**
     * @return int
     */
    public function getOrigamount()
    {
        return $this->origamount;
    }

    /**
     * @return mixed
     */
    public function getOrigcurrency()
    {
        return $this->origcurrency;
    }

    /**
     * @param int $origamount
     */
    public function setOrigamount($origamount)
    {
        $this->origamount = $origamount;
    }

    /**
     * @param mixed $origcurrency
     */
    public function setOrigcurrency($origcurrency)
    {
        $this->origcurrency = $origcurrency;
    }
    /**
     * @param mixed $url
     */
    public function setUrl($url)
    {
        $this->url = $url;
    }

    /**
     * @return mixed
     */
    public function getUrl()
    {
        return $this->url;
    }
    /**
     * @param mixed $operation
     */
    public function setOperation($operation)
    {
        $this->operation = $operation;
    }
    /**
     * @param mixed $status
     */
    public function setStatus($status)
    {
        $this->status = $status;
    }

    /**
     * @return mixed
     */
    public function getStatus()
    {
        return $this->status;
    }
    /**
     * @param Customer $customer
     */
    public function setCustomer(Customer $customer)
    {
        $this->customer = $customer;
       // $this->customer->;
    }
    /**
     * @param mixed $transdata
     */
    public function setTransdata(TransData $transdata)
    {
        $this->transdata = $transdata;
    }

    /**
     * @param Card $card
     */
    public function setCard(Card $card)
    {
        $this->card = $card;
    }
    /**
     * @param mixed $xid
     */
    public function setXid($xid)
    {
        $this->xid = $xid;
    }

     /**
     * @param mixed $amount
     */
    public function setAmount($amount)
    {
        $this->amount = $amount;
    }


    /**
     * @param mixed $currency
     */
    public function setCurrency($currency)
    {
        $this->currency = $currency;
    }

    /**
     * @param mixed $description
     */
    public function setDescription($description)
    {
        $this->description = htmlentities( $description);
    }


    /**
     * @param mixed $language
     */
    public function setLanguage($language)
    {
        $this->language = $language;
    }


    /**
     * @param mixed $orderid
     */
    public function setOrderid($orderid)
    {
        $this->orderid = $orderid;
    }

    /**
     * @return mixed
     */
    public function getAmount()
    {
        return $this->amount;
    }

    /**
     * @return mixed
     */
    public function getCurrency()
    {
        return $this->currency;
    }

    /**
     * @return mixed
     */
    public function getDescription()
    {
        return $this->description;
    }


    /**
     * @return mixed
     */
    public function getLanguage()
    {
        return $this->language;
    }
    /**
     * @return int
     */
    public function getOrderdate()
    {
        return $this->orderdate;
    }

    /**
     * @return mixed
     */
    public function getOrderid()
    {
        return $this->orderid;
    }

    /**
     * @return string
     */
    public function getOperationtype()
    {
        return $this->operationtype;
    }

    /**
     * @return mixed
     */
    public function getXid()
    {
        return $this->xid;
    }

    /**
     * @param int $orderdate
     */
    public function setOrderdate($orderdate)
    {
        $this->orderdate = $orderdate;
    }

    /**
     * @param string $operationtype
     */
    public function setOperationtype($operationtype)
    {
        $this->operationtype = $operationtype;
    }

    /**
     * @return mixed
     */
    public function getOrderstatus()
    {
        return $this->orderstatus;
    }

    /**
     * @return mixed
     */
    public function getSessionid()
    {
        return $this->sessionid;
    }

    /**
     * @param mixed $orderstatus
     */
    public function setOrderstatus($orderstatus)
    {
        $this->$orderstatus = $orderstatus;
    }


    /**
     * @return mixed
     */
    public function getFee()
    {
        return $this->fee;
    }

    /**
     * @param mixed $fee
     */
    public function setFee($fee)
    {
        $this->fee = $fee;
    }

    /**
     * @return mixed
     */
    public function getMerchantid()
    {
        return $this->merchantid;
    }

    /**
     * @param mixed $merchantid
     */
    public function setMerchantid($merchantid)
    {
        $this->merchantid = $merchantid;
    }
    /**
     * @param mixed $sessionid
     */
    public function setSessionid($sessionid)
    {
        $this->sessionid = $sessionid;
    }
}