<?php
/**
 * Created by PhpStorm.
 * User: arevkina
 * Date: 04.10.2017
 * Time: 15:42
 */

namespace Skytech;
use SimpleXMLElement;
use XMLWriter;

include 'purchase.php';

class Order
{
    public  $operation;
    private $orderid; /** @var int unique order id generated by TWEC PG */
    private $xid; /** @var int unique order id  generated by merchant */
    private $orderdate;
    private $language;
    private $amount;
    private $currency;
    private $description;
    private $operationtype;
    private $orderstatus;
    private $sessionid;
    private $merchantid;
    private $fee;
    private $url;
    private $declineurl;
    private $cancelurl;
    private $approveurl;
    public $customer; /** @var Customer info*/
    public $transdata;
    public $card;
    private $status; /** @var  int request status*/

    function __construct(Customer $customer,TransData $transdata,Card $card)
    {
        $this->orderdate = time();
        $this->operationtype = "Purchase";
        $this->customer = $customer;
        $this->transdata = $transdata;
        $this->card = $card;
    }

    /**
     * @param mixed $url
     */
    public function setUrl($url)
    {
        $this->url = $url;
    }

    /**
     * @return mixed
     */
    public function getUrl()
    {
        return $this->url;
    }
    /**
     * @param mixed $operation
     */
    public function setOperation($operation)
    {
        $this->operation = $operation;
    }
    /**
     * @param mixed $status
     */
    public function setStatus($status)
    {
        $this->status = $status;
    }

    /**
     * @return mixed
     */
    public function getStatus()
    {
        return $this->status;
    }
    /**
     * @param Customer $customer
     */
    public function setCustomer(Customer $customer)
    {
        $this->customer = $customer;
       // $this->customer->;
    }
    /**
     * @param mixed $transdata
     */
    public function setTransdata(TransData $transdata)
    {
        $this->transdata = $transdata;
    }

    /**
     * @param Card $card
     */
    public function setCard(Card $card)
    {
        $this->card = $card;
    }
    /**
     * @param mixed $xid
     */
    public function setXid($xid)
    {
        $this->xid = $xid;
    }

     /**
     * @param mixed $amount
     */
    public function setAmount($amount)
    {
        $this->amount = $amount;
    }


    /**
     * @param mixed $currency
     */
    public function setCurrency($currency)
    {
        $this->currency = $currency;
    }

    /**
     * @param mixed $description
     */
    public function setDescription($description)
    {
        $this->description = $description;
    }


    /**
     * @param mixed $language
     */
    public function setLanguage($language)
    {
        $this->language = $language;
    }


    /**
     * @param mixed $orderid
     */
    public function setOrderid($orderid)
    {
        $this->orderid = $orderid;
    }

    /**
     * @return mixed
     */
    public function getAmount()
    {
        return $this->amount;
    }

    /**
     * @return mixed
     */
    public function getCurrency()
    {
        return $this->currency;
    }

    /**
     * @return mixed
     */
    public function getDescription()
    {
        return $this->description;
    }


    /**
     * @return mixed
     */
    public function getLanguage()
    {
        return $this->language;
    }
    /**
     * @return int
     */
    public function getOrderdate()
    {
        return $this->orderdate;
    }

    /**
     * @return mixed
     */
    public function getOrderid()
    {
        return $this->orderid;
    }

    /**
     * @return string
     */
    public function getOperationtype()
    {
        return $this->operationtype;
    }

    /**
     * @return mixed
     */
    public function getXid()
    {
        return $this->xid;
    }

    /**
     * @param int $orderdate
     */
    public function setOrderdate($orderdate)
    {
        $this->orderdate = $orderdate;
    }

    /**
     * @param string $operationtype
     */
    public function setOperationtype($operationtype)
    {
        $this->operationtype = $operationtype;
    }

    /**
     * @return mixed
     */
    public function getOrderstatus()
    {
        return $this->orderstatus;
    }

    /**
     * @return mixed
     */
    public function getSessionid()
    {
        return $this->sessionid;
    }

    /**
     * @param mixed $orderstatus
     */
    public function setOrderstatus($orderstatus)
    {
        $this->$orderstatus = $orderstatus;
    }

    /**
     * @param mixed $approveurl
     */
    public function setApproveurl($approveurl)
    {
        $this->approveurl = $approveurl;
    }

    /**
     * @param mixed $cancelurl
     */
    public function setCancelurl($cancelurl)
    {
        $this->cancelurl = $cancelurl;
    }

    /**
     * @param mixed $declineurl
     */
    public function setDeclineurl($declineurl)
    {
        $this->declineurl = $declineurl;
    }

    /**
     * @return mixed
     */
    public function getApproveurl()
    {
        return $this->approveurl;
    }

    /**
     * @return mixed
     */
    public function getDeclineurl()
    {
        return $this->declineurl;
    }

    /**
     * @return mixed
     */
    public function getCancelurl()
    {
        return $this->cancelurl;
    }

    /**
     * @return mixed
     */
    public function getFee()
    {
        return $this->fee;
    }

    /**
     * @param mixed $fee
     */
    public function setFee($fee)
    {
        $this->fee = $fee;
    }

    /**
     * @return mixed
     */
    public function getMerchantid()
    {
        return $this->merchantid;
    }

    /**
     * @param mixed $merchantid
     */
    public function setMerchantid($merchantid)
    {
        $this->merchantid = $merchantid;
    }
    /**
     * @param mixed $sessionid
     */
    public function setSessionid($sessionid)
    {
        $this->sessionid = $sessionid;
    }
}